// Generated by scripts/gen-presets.mjs from static/data/base.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { BaseConfig } from "../types.js";

/** Default board size and draw flags. */
export const baseConfig: BaseConfig = {
  size: { width: 60, height: 44 },
  half_way_lines: { draw: true },
  grid: { draw: true },
};
