// Generated by scripts/gen-presets.mjs from static/data/deployment/*.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { DeploymentConfig } from "../types.js";

/** Crucible of Battle, from `static/data/deployment/crucible_of_battle.yml`. */
export const crucibleOfBattle: DeploymentConfig = {
  name: "Crucible of Battle",
  home_edge: "short",
  attacker: { deployment_zone: [[60, 0], [60, 44], [30, 0]] },
  defender: { deployment_zone: [[30, 44], [0, 44], [0, 0]] },
};

/** Dawn of War, from `static/data/deployment/dawn_of_war.yml`. */
export const dawnOfWar: DeploymentConfig = {
  name: "Dawn of War",
  home_edge: "long",
  attacker: { deployment_zone: [[0, 0], [0, 12], [60, 12], [60, 0]] },
  defender: { deployment_zone: [[0, 32], [0, 44], [60, 44], [60, 32]] },
};

/** Hammer and Anvil, from `static/data/deployment/hammer_and_anvil.yml`. */
export const hammerAndAnvil: DeploymentConfig = {
  name: "Hammer and Anvil",
  home_edge: "short",
  attacker: { deployment_zone: [[60, 0], [42, 0], [42, 44], [60, 44]] },
  defender: { deployment_zone: [[18, 0], [0, 0], [0, 44], [18, 44]] },
};

/** Search and Destroy, from `static/data/deployment/search_and_destroy.yml`. */
export const searchAndDestroy: DeploymentConfig = {
  name: "Search and Destroy",
  home_edge: "long",
  attacker: {
    mask_center: 9,
    deployment_zone: [[60, 0], [60, 22], [30, 22], [30, 0]],
  },
  defender: {
    mask_center: 9,
    deployment_zone: [[30, 22], [30, 44], [0, 44], [0, 22]],
  },
};

/** Sweeping Engagement, from `static/data/deployment/sweeping_engagement.yml`. */
export const sweepingEngagement: DeploymentConfig = {
  name: "Sweeping Engagement",
  home_edge: "long",
  attacker: {
    deployment_zone: [[60, 44], [0, 44], [0, 30], [30, 30], [30, 36], [60, 36]],
  },
  defender: {
    deployment_zone: [[0, 0], [60, 0], [60, 14], [30, 14], [30, 8], [0, 8]],
  },
};

/** Tipping Point, from `static/data/deployment/tipping_point.yml`. */
export const tippingPoint: DeploymentConfig = {
  name: "Tipping Point",
  home_edge: "short",
  attacker: {
    deployment_zone: [
      [0, 44],
      [0, 0],
      [12, 0],
      [12, 22],
      [20, 22],
      [20, 32],
      [20, 44],
    ],
  },
  defender: {
    deployment_zone: [[60, 0], [60, 44], [48, 44], [48, 22], [40, 22], [40, 0]],
  },
};

/** All built-in missions keyed by id (the deployment YAML filename stem). */
export const missions = {
  crucible_of_battle: crucibleOfBattle,
  dawn_of_war: dawnOfWar,
  hammer_and_anvil: hammerAndAnvil,
  search_and_destroy: searchAndDestroy,
  sweeping_engagement: sweepingEngagement,
  tipping_point: tippingPoint,
} satisfies Record<string, DeploymentConfig>;

/** The id of a built-in mission. */
export type MissionId = keyof typeof missions;
