// Generated by scripts/gen-presets.mjs from static/data/deployment/*.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { DeploymentConfig } from "../types.js";

/** Crucible of Battle, from `static/data/deployment/crucible_of_battle.yml`. */
export const crucibleOfBattle: DeploymentConfig = {
  name: "Crucible of Battle",
  home_edge: "short",
  attacker: {
    deployment_zone: [{ x: 60, y: 0 }, { x: 60, y: 44 }, { x: 30, y: 0 }],
  },
  defender: {
    deployment_zone: [{ x: 30, y: 44 }, { x: 0, y: 44 }, { x: 0, y: 0 }],
  },
};

/** Dawn of War, from `static/data/deployment/dawn_of_war.yml`. */
export const dawnOfWar: DeploymentConfig = {
  name: "Dawn of War",
  home_edge: "long",
  attacker: {
    deployment_zone: [
      { x: 0, y: 0 },
      { x: 0, y: 12 },
      { x: 60, y: 12 },
      { x: 60, y: 0 },
    ],
  },
  defender: {
    deployment_zone: [
      { x: 0, y: 32 },
      { x: 0, y: 44 },
      { x: 60, y: 44 },
      { x: 60, y: 32 },
    ],
  },
};

/** Hammer and Anvil, from `static/data/deployment/hammer_and_anvil.yml`. */
export const hammerAndAnvil: DeploymentConfig = {
  name: "Hammer and Anvil",
  home_edge: "short",
  attacker: {
    deployment_zone: [
      { x: 60, y: 0 },
      { x: 42, y: 0 },
      { x: 42, y: 44 },
      { x: 60, y: 44 },
    ],
  },
  defender: {
    deployment_zone: [
      { x: 18, y: 0 },
      { x: 0, y: 0 },
      { x: 0, y: 44 },
      { x: 18, y: 44 },
    ],
  },
};

/** Search and Destroy, from `static/data/deployment/search_and_destroy.yml`. */
export const searchAndDestroy: DeploymentConfig = {
  name: "Search and Destroy",
  home_edge: "long",
  attacker: {
    mask_center: 9,
    deployment_zone: [
      { x: 60, y: 0 },
      { x: 60, y: 22 },
      { x: 30, y: 22 },
      { x: 30, y: 0 },
    ],
  },
  defender: {
    mask_center: 9,
    deployment_zone: [
      { x: 30, y: 22 },
      { x: 30, y: 44 },
      { x: 0, y: 44 },
      { x: 0, y: 22 },
    ],
  },
};

/** Sweeping Engagement, from `static/data/deployment/sweeping_engagement.yml`. */
export const sweepingEngagement: DeploymentConfig = {
  name: "Sweeping Engagement",
  home_edge: "long",
  attacker: {
    deployment_zone: [
      { x: 60, y: 44 },
      { x: 0, y: 44 },
      { x: 0, y: 30 },
      { x: 30, y: 30 },
      { x: 30, y: 36 },
      { x: 60, y: 36 },
    ],
  },
  defender: {
    deployment_zone: [
      { x: 0, y: 0 },
      { x: 60, y: 0 },
      { x: 60, y: 14 },
      { x: 30, y: 14 },
      { x: 30, y: 8 },
      { x: 0, y: 8 },
    ],
  },
};

/** Tipping Point, from `static/data/deployment/tipping_point.yml`. */
export const tippingPoint: DeploymentConfig = {
  name: "Tipping Point",
  home_edge: "short",
  attacker: {
    deployment_zone: [
      { x: 0, y: 44 },
      { x: 0, y: 0 },
      { x: 12, y: 0 },
      { x: 12, y: 22 },
      { x: 20, y: 22 },
      { x: 20, y: 32 },
      { x: 20, y: 44 },
    ],
  },
  defender: {
    deployment_zone: [
      { x: 60, y: 0 },
      { x: 60, y: 44 },
      { x: 48, y: 44 },
      { x: 48, y: 22 },
      { x: 40, y: 22 },
      { x: 40, y: 0 },
    ],
  },
};

/** All built-in missions keyed by id (the deployment YAML filename stem). */
export const missions = {
  crucible_of_battle: crucibleOfBattle,
  dawn_of_war: dawnOfWar,
  hammer_and_anvil: hammerAndAnvil,
  search_and_destroy: searchAndDestroy,
  sweeping_engagement: sweepingEngagement,
  tipping_point: tippingPoint,
} satisfies Record<string, DeploymentConfig>;

/** The id of a built-in mission. */
export type MissionId = keyof typeof missions;
