// Generated by scripts/gen-presets.mjs from static/data/terrain/combined.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { TerrainLayoutMeta } from "../event-matrix.js";

/** Matchup metadata for each bundled layout, without the geometry. */
export const gwTerrainIndex: Record<string, TerrainLayoutMeta> = {
  "bm-assets-vs-assets-01": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Priority Assets", "Priority Assets"],
  },
  "bm-assets-vs-assets-02": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Priority Assets", "Priority Assets"],
  },
  "bm-assets-vs-assets-03": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Priority Assets", "Priority Assets"],
  },
  "bm-disrupt-vs-assets-01": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Disruption", "Priority Assets"],
  },
  "bm-disrupt-vs-assets-02": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Disruption", "Priority Assets"],
  },
  "bm-disrupt-vs-assets-03": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Disruption", "Priority Assets"],
  },
  "bm-disrupt-vs-disrupt-01": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Disruption", "Disruption"],
  },
  "bm-disrupt-vs-disrupt-02": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Disruption", "Disruption"],
  },
  "bm-disrupt-vs-disrupt-03": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Disruption", "Disruption"],
  },
  "bm-disrupt-vs-recon-01": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Disruption", "Reconnaissance"],
  },
  "bm-disrupt-vs-recon-02": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Disruption", "Reconnaissance"],
  },
  "bm-disrupt-vs-recon-03": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Disruption", "Reconnaissance"],
  },
  "bm-purge-vs-assets-01": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Purge the Foe", "Priority Assets"],
  },
  "bm-purge-vs-assets-02": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Purge the Foe", "Priority Assets"],
  },
  "bm-purge-vs-assets-03": {
    deployment_pattern_id: "hammer-and-anvil",
    dispositions: ["Purge the Foe", "Priority Assets"],
  },
  "bm-purge-vs-disrupt-01": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Disruption", "Purge the Foe"],
  },
  "bm-purge-vs-disrupt-02": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Disruption", "Purge the Foe"],
  },
  "bm-purge-vs-disrupt-03": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Disruption", "Purge the Foe"],
  },
  "bm-purge-vs-purge-01": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Purge the Foe", "Purge the Foe"],
  },
  "bm-purge-vs-purge-02": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Purge the Foe", "Purge the Foe"],
  },
  "bm-purge-vs-purge-03": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Purge the Foe", "Purge the Foe"],
  },
  "bm-purge-vs-recon-01": {
    deployment_pattern_id: "hammer-and-anvil",
    dispositions: ["Purge the Foe", "Reconnaissance"],
  },
  "bm-purge-vs-recon-02": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Purge the Foe", "Reconnaissance"],
  },
  "bm-purge-vs-recon-03": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Purge the Foe", "Reconnaissance"],
  },
  "bm-recon-vs-assets-01": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Priority Assets", "Reconnaissance"],
  },
  "bm-recon-vs-assets-02": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Priority Assets", "Reconnaissance"],
  },
  "bm-recon-vs-assets-03": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Priority Assets", "Reconnaissance"],
  },
  "bm-recon-vs-recon-01": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Reconnaissance", "Reconnaissance"],
  },
  "bm-recon-vs-recon-02": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Reconnaissance", "Reconnaissance"],
  },
  "bm-recon-vs-recon-03": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Reconnaissance", "Reconnaissance"],
  },
  "bm-take-vs-disrupt-01": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Take and Hold", "Disruption"],
  },
  "bm-take-vs-disrupt-02": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Take and Hold", "Disruption"],
  },
  "bm-take-vs-disrupt-03": {
    deployment_pattern_id: "hammer-and-anvil",
    dispositions: ["Take and Hold", "Disruption"],
  },
  "bm-take-vs-prio-01": {
    deployment_pattern_id: "crucible-of-battle",
    dispositions: ["Take and Hold", "Priority Assets"],
  },
  "bm-take-vs-prio-02": {
    deployment_pattern_id: "hammer-and-anvil",
    dispositions: ["Take and Hold", "Priority Assets"],
  },
  "bm-take-vs-prio-03": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Take and Hold", "Priority Assets"],
  },
  "bm-take-vs-purge-01": {
    deployment_pattern_id: "sweeping-engagement",
    dispositions: ["Take and Hold", "Purge the Foe"],
  },
  "bm-take-vs-purge-02": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Take and Hold", "Purge the Foe"],
  },
  "bm-take-vs-purge-03": {
    deployment_pattern_id: "hammer-and-anvil",
    dispositions: ["Take and Hold", "Purge the Foe"],
  },
  "bm-take-vs-recon-01": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Take and Hold", "Reconnaissance"],
  },
  "bm-take-vs-recon-02": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Take and Hold", "Reconnaissance"],
  },
  "bm-take-vs-recon-03": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Take and Hold", "Reconnaissance"],
  },
  "bm-take-vs-take-01": {
    deployment_pattern_id: "tipping-point",
    dispositions: ["Take and Hold", "Take and Hold"],
  },
  "bm-take-vs-take-02": {
    deployment_pattern_id: "dawn-of-war",
    dispositions: ["Take and Hold", "Take and Hold"],
  },
  "bm-take-vs-take-03": {
    deployment_pattern_id: "search-and-destroy",
    dispositions: ["Take and Hold", "Take and Hold"],
  },
};
