// Generated by scripts/gen-presets.mjs from static/data/terrain/gw.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { TerrainConfig } from "../terrain-config.js";

/** Built-in building templates and numbered layouts. */
export const gwTerrain: TerrainConfig = {
  templates: {
    "large-area": { width: 7, height: 11 },
    "small-area": { width: 4, height: 6 },
    pipes: { width: 6, height: 2 },
    "large-pipes": { width: 10, height: 2.5 },
    shoe: { points: [[0, 0], [8, 0], [2, 11.5], [0, 11.5]] },
  },
  layout: {
    "1": {
      buildings: [
        { type: "large-pipes", corners: { BL: [12, 6], TL: [14.5, 6] } },
        { type: "large-area", corners: { TL: [18.5, 0], TR: [25.5, 0] } },
        { type: "large-area", corners: { TR: [17, 19.5] } },
      ],
    },
  },
};
