// Generated by scripts/gen-presets.mjs from static/data/theme.yml.
// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.

import type { Theme } from "../theme.js";

/** Default SVG styling for every rendered element. */
export const baseTheme: Theme = {
  background: { fill: "#f4f1e8" },
  half_way_lines: {
    stroke: "black",
    stroke_dasharray: "0.5 0.5",
    stroke_width: 0.2,
    opacity: 0.5,
  },
  territory: { stroke: "black", stroke_width: 0.3, opacity: 0.6 },
  deployment: {
    attacker: { fill: "#cf4b33", stroke: "none", stroke_width: 0.4 },
    defender: { fill: "#7d8b7f", stroke: "none", stroke_width: 0.4 },
  },
  building: {
    group: { opacity: 1 },
    template: {
      default: {
        "vector-effect": "non-scaling-stroke",
        stroke: "black",
        stroke_width: 1.2,
        fill: "#808080",
        opacity: 1,
      },
      pipe: {
        "vector-effect": "non-scaling-stroke",
        fill: "#b9772e",
        stroke: "black",
        stroke_width: 1.5,
      },
      barricade: {
        "vector-effect": "non-scaling-stroke",
        fill: "#c9a86a",
        stroke: "black",
        stroke_width: 1.5,
      },
    },
  },
  grid: {
    opacity: 0.3,
    stroke: "black",
    stroke_width: 0.15,
    stroke_dasharray: "0.1 0.1",
  },
  objective: {
    marker: { fill: "#33312c", stroke: "white", stroke_width: 0.3 },
    label: { font_size: 2, fill: "white" },
  },
  annotation: {
    text: { font_size: 1.5, fill: "black" },
    text_outline: { stroke: "white", stroke_width: 0.3, paint_order: "stroke" },
    arrow: { stroke: "black", stroke_width: 0.4 },
  },
  area_terrain: {
    default: {
      fill: "rgba(128,128,128,0.2)",
      stroke: "#808080",
      stroke_width: 0.3,
    },
    Forest: {
      fill: "rgba(74,140,60,0.3)",
      stroke: "#2c5822",
      stroke_width: 0.3,
    },
    Crater: {
      fill: "rgba(110,69,26,0.3)",
      stroke: "#6e451a",
      stroke_width: 0.3,
    },
    Rubble: {
      fill: "rgba(154,160,166,0.3)",
      stroke: "#5b6068",
      stroke_width: 0.3,
    },
    feature: {
      fill: "rgba(128,128,128,0.55)",
      stroke: "#5b6068",
      stroke_width: 0.3,
    },
    pipe: { fill: "#b9772e", stroke: "#6e451a", stroke_width: 0.3 },
    barricade: { fill: "#c9a86a", stroke: "#7d6233", stroke_width: 0.3 },
  },
  icon: {
    circle: { fill: "#e8dcc0", stroke: "#33312c", stroke_width: 0.25 },
    glyph: { fill: "#33312c" },
  },
  feature: {
    stroke_width: 0.2,
    palette: {
      stone: { fill: "#9aa0a6", accent: "#5b6068" },
      rust: { fill: "#b9772e", accent: "#6e451a" },
      sand: { fill: "#c9a86a", accent: "#7d6233" },
      green: { fill: "#4a8c3c", accent: "#2c5822" },
      gunmetal: { fill: "#5b6068", accent: "#3f444a" },
      teal: { fill: "#2f6b73", accent: "#1a3d42" },
      bone: { fill: "#e8dcc0", accent: "#9a8f76" },
    },
  },
};
