// Generates the typed preset modules in `src/presets/` from the YAML the
// browser app loads (`static/data/`). The YAML is the single source of
// truth; run `pnpm gen:presets` after editing it. `--check` exits non-zero
// when the committed presets are stale (used by CI).

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import * as yaml from "js-yaml";

const dataDir = new URL("../static/data/", import.meta.url);
const presetsDir = new URL("../src/presets/", import.meta.url);

const MAX_WIDTH = 80;

const loadYaml = (relPath) =>
  yaml.load(readFileSync(new URL(relPath, dataDir), "utf8"));

const camelCase = (id) => id.replace(/_([a-z])/g, (_, c) => c.toUpperCase());

const isIdentifier = (key) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
const renderKey = (key) => (isIdentifier(key) ? key : JSON.stringify(key));

function token(value) {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value === null) return "null";
  throw new Error(`Cannot serialize value: ${String(value)}`);
}

/** Single-line form of a value, used to decide whether it fits on one line. */
function inline(value) {
  if (Array.isArray(value)) {
    return `[${value.map(inline).join(", ")}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value).map(
      ([key, val]) => `${renderKey(key)}: ${inline(val)}`,
    );
    return entries.length ? `{ ${entries.join(", ")} }` : "{}";
  }
  return token(value);
}

/**
 * Serializes a value as a TS literal, expanding to multiple lines only when
 * the inline form would overflow `MAX_WIDTH`. `column` is where the value
 * begins on its line; `indent` is the current indentation string.
 */
function render(value, column, indent) {
  const flat = inline(value);
  if (column + flat.length + 1 <= MAX_WIDTH) return flat;

  const childIndent = `${indent}  `;
  if (Array.isArray(value)) {
    const items = value.map(
      (item) =>
        `${childIndent}${render(item, childIndent.length, childIndent)},`,
    );
    return `[\n${items.join("\n")}\n${indent}]`;
  }
  if (value && typeof value === "object") {
    const items = Object.entries(value).map(([key, val]) => {
      const prefix = `${childIndent}${renderKey(key)}: `;
      return `${prefix}${render(val, prefix.length, childIndent)},`;
    });
    return `{\n${items.join("\n")}\n${indent}}`;
  }
  return flat;
}

function header(source) {
  return (
    `// Generated by scripts/gen-presets.mjs from ${source}.\n` +
    "// Do not edit by hand — run `pnpm gen:presets` after editing the YAML.\n\n"
  );
}

function declaration(name, type, data, doc) {
  const decl = `export const ${name}: ${type} = `;
  return `${doc}\n${decl}${render(data, decl.length, "")};\n`;
}

function buildBase() {
  return (
    header("static/data/base.yml") +
    'import type { BaseConfig } from "../types.js";\n\n' +
    declaration(
      "baseConfig",
      "BaseConfig",
      loadYaml("base.yml"),
      "/** Default board size and draw flags. */",
    )
  );
}

function buildTerrain() {
  // The terrain config is split across two files: templates-simple.yml holds
  // the building templates, and combined.yml (generated by
  // scripts/convert-40kdc-terrain.mjs from gw.yml + the ported 40kdc layouts)
  // holds the layouts. Merge them into one TerrainConfig — the same shape the
  // app/editor assemble at runtime.
  const terrain = {
    ...loadYaml("terrain/templates-simple.yml"),
    ...loadYaml("terrain/combined.yml"),
  };
  return (
    header("static/data/terrain/templates-simple.yml + combined.yml") +
    'import type { TerrainConfig } from "../terrain-config.js";\n\n' +
    declaration(
      "gwTerrain",
      "TerrainConfig",
      terrain,
      "/** Built-in templates and layouts (gw.yml demo + ported 40kdc pieces). */",
    )
  );
}

function buildTemplatesReal() {
  // The detailed GW footprints, the higher-fidelity counterpart to
  // templates-simple.yml (which buildTerrain bakes into gwTerrain). Exported on
  // its own so consumers can swap it onto gwTerrain: `{ ...gwTerrain,
  // ...gwTemplatesReal }` — the real templates win, the layouts stay shared.
  return (
    header("static/data/terrain/templates-real.yml") +
    'import type { TerrainConfig } from "../terrain-config.js";\n\n' +
    declaration(
      "gwTemplatesReal",
      'Pick<TerrainConfig, "templates">',
      loadYaml("terrain/templates-real.yml"),
      "/** Detailed GW footprints; swap onto gwTerrain: `{ ...gwTerrain, ...gwTemplatesReal }`. */",
    )
  );
}

function buildMissions() {
  const ids = readdirSync(new URL("deployment/", dataDir))
    .filter((file) => file.endsWith(".yml"))
    .map((file) => file.replace(/\.yml$/, ""))
    .sort();

  let out =
    header("static/data/deployment/*.yml") +
    'import type { DeploymentConfig } from "../types.js";\n\n';

  for (const id of ids) {
    const data = loadYaml(`deployment/${id}.yml`);
    const doc = `/** ${data.name}, from \`static/data/deployment/${id}.yml\`. */`;
    out += `${declaration(camelCase(id), "DeploymentConfig", data, doc)}\n`;
  }

  const record = ids
    .map((id) => `  ${renderKey(id)}: ${camelCase(id)},`)
    .join("\n");
  out +=
    "/** All built-in missions keyed by id (the deployment YAML filename stem). */\n" +
    `export const missions = {\n${record}\n} satisfies Record<string, DeploymentConfig>;\n\n` +
    "/** The id of a built-in mission. */\n" +
    "export type MissionId = keyof typeof missions;\n";

  return out;
}

function buildEventMatrix() {
  // The YAML wraps the pairings under a top-level `matrix:` key; the preset
  // exports just that map (see static/data/event_companion_matrix.yml).
  const { matrix } = loadYaml("event_companion_matrix.yml");
  return (
    header("static/data/event_companion_matrix.yml") +
    'import type { EventMatrix } from "../event-matrix.js";\n\n' +
    declaration(
      "eventMatrix",
      "EventMatrix",
      matrix,
      "/** Force-disposition pairings -> layout -> deployment (event companion). */",
    )
  );
}

function buildTheme() {
  return (
    header("static/data/theme.yml") +
    'import type { Theme } from "../theme.js";\n\n' +
    declaration(
      "baseTheme",
      "Theme",
      loadYaml("theme.yml"),
      "/** Default SVG styling for every rendered element. */",
    )
  );
}

const targets = [
  ["base.ts", buildBase()],
  ["missions.ts", buildMissions()],
  ["terrain.ts", buildTerrain()],
  ["templates-real.ts", buildTemplatesReal()],
  ["event-matrix.ts", buildEventMatrix()],
  ["theme.ts", buildTheme()],
];

const check = process.argv.includes("--check");
const stale = [];

for (const [name, content] of targets) {
  const path = new URL(name, presetsDir);
  if (!check) {
    writeFileSync(path, content);
    console.log(`wrote src/presets/${name}`);
    continue;
  }
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // file doesn't exist or can't be read; treat as empty
  }
  if (current !== content) stale.push(name);
}

if (check && stale.length) {
  console.error(
    `Stale generated presets: ${stale.join(", ")}\n` +
      "Run `pnpm gen:presets` and commit the result.",
  );
  process.exit(1);
}
if (check) console.log("Generated presets are up to date.");
